### PR TITLE
responsive for mobile users

### PR DESCRIPTION
**Pull request by sinistersnare**
Hey, I use mobile a lot, and this site would be better if it used relative width instead of a fixed width design.

Any ideas on other small changes? Not much of a CSS guy, but I wanted this done, so I did it... 

Thanks!

### CODE REVIEW

**Comment by steveklabnik** [comment]
I don't think this is the right way to fix this problem. You don't want text to go much wider than a certain size for readability purposes. On a 30' monitor, it'd be unreadable.

That said, I'm not sure what the best way to fix this is, outside of media queries?

**Comment by sinistersnare** [comment]
Thats a good point. Well, I am not a CSS guy, I just wanted to bring this up, because I go on mobile a lot, and non-mobile friendly sites make me sad.

**Comment by steveklabnik** [comment]
Yes! It's certainly an issue.

**Comment by steveklabnik** [comment]
I think https://github.com/wycats/cargo-website/pull/18 solves this problem better, actually. Check it out!

**Comment by wycats** [comment]
Merged #18

**Pull request closed without merging**
