### PR TITLE
document local overrides in the guide

### PR DESCRIPTION
**Pull request by steveklabnik**

### CODE REVIEW

**Comment by wycats** [comment]
@steveklabnik can you use better names than "foo" and "bar"? I find people can more easily understand concepts with concrete naming :smile:

**Comment by steveklabnik** [comment]
I'm open to any suggestions. I agree it could be better. So we have a real example?

**Comment by ghost** [comment]
Well, a real example will be much better than foo and bar.,., There are lots of Rust projects, for eg. Piston which can make a very good real example ,.,.,

**Comment by wycats** [comment]
I added a better example and manually merged this :smile:

**Comment by steveklabnik** [comment]
:sweat_smile: :heart:

**Pull request closed without merging**
